//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// EffectTool.rc에서 사용되고 있습니다.
//
#define IDOK2                           2
#define IDC_P_Button_Reset              2
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define IDR_MAINFRAME                   127
#define IDR_MAINFRAME_256               129
#define IDR_EffectToolTYPE              130
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_CUSTOMIZE               202
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_EDIT_MENU                   306
#define IDD_DIALOG_Inspector            310
#define IDD_DIALOG_Preset               312
#define IDD_DIALOG_Hierarchy            315
#define IDD_DIALOG_CRenderer            321
#define IDD_DIALOG_CParticle            323
#define IDD_DIALOG_CAnimation           325
#define IDD_DIALOG_Null                 327
#define IDD_DIALOG_Collider             331
#define IDD_DIALOG_CTransformer         333
#define IDC_AnimList                    1005
#define IDC_isEnable                    1006
#define IDC_isBillBoard                 1007
#define IDC_AnimRate                    1008
#define IDC_PosX                        1009
#define IDC_ScaleX                      1010
#define IDC_R_onCubeMap                 1010
#define IDC_C_MaxX                      1010
#define IDC_PosY                        1011
#define IDC_PosZ                        1012
#define IDC_RotX                        1013
#define IDC_C_MaxY                      1013
#define IDC_RotY                        1014
#define IDC_RotX2                       1014
#define IDC_R_ColorY                    1014
#define IDC_C_MaxZ                      1014
#define IDC_RotZ                        1015
#define IDC_RotX3                       1015
#define IDC_R_ColorZ                    1015
#define IDC_C_DirectionX                1015
#define IDC_ScaleY                      1016
#define IDC_RotX4                       1016
#define IDC_R_ColorW                    1016
#define IDC_C_DirectionY                1016
#define IDC_ScaleZ                      1017
#define IDC_C_DirectionZ                1017
#define IDC_ObjectName                  1018
#define IDC_AnimPosX                    1019
#define ID_Delete                       1020
#define IDC_AnimPosY                    1020
#define ID_Duplicate                    1021
#define IDC_AnimPosZ                    1021
#define IDC_ObjectList                  1022
#define IDC_AnimRotX                    1022
#define ID_Export                       1022
#define IDC_SPIN                        1023
#define IDC_AnimRotY                    1023
#define ID_Export2                      1023
#define ID_Create                       1024
#define IDC_AnimRotZ                    1024
#define ID_Load                         1025
#define IDC_AnimScaleX                  1025
#define IDC_isStatic                    1026
#define IDC_AnimScaleY                  1027
#define IDC_AnimScaleZ                  1028
#define IDC_AnimFPS                     1029
#define IDC_AnimFrame                   1030
#define IDC_TreeList                    1034
#define IDC_BUTTON1                     1037
#define IDC_Focus                       1037
#define IDC_BUTTON2                     1038
#define IDC_Composite                   1038
#define IDC_PresetList                  1040
#define ID_PresetLoad                   1041
#define ID_PresetApply                  1042
#define IDC_IntervalMin                 1043
#define IDC_P_Interval                  1043
#define ID_R_DiffuseApply               1043
#define ID_R_DiffuseApply2              1044
#define IDC_P_LifeTime                  1044
#define IDC_ANIMATE1                    1045
#define IDC_Inspector_Components        1047
#define ID_R_DiffuseReset               1050
#define ID_R_NormalApply                1051
#define ID_R_NormalReset                1052
#define IDC_P_MaxCount                  1053
#define ID_R_EnviApply                  1053
#define IDC_P_Button_Update             1054
#define ID_R_EnviReset                  1054
#define ID_Inspector_CompDelete         1055
#define ID_R_EnviApply2                 1055
#define ID_Inspector_CompAdd            1056
#define ID_R_EnviReset2                 1056
#define IDC_AnimPosY2                   1057
#define ID_Inspector_SetProto           1057
#define ID_R_ShadowApply                1057
#define IDC_LifeMin                     1058
#define IDC_P_DirMinX                   1058
#define IDC_Inspector_CompPreset        1058
#define ID_R_LightApply                 1058
#define ID_C_Reset                      1058
#define IDC_LifeMax                     1059
#define IDC_P_DirMaxX                   1059
#define IDC_P_PositionMinX              1060
#define IDC_P_isBillBoard               1061
#define IDC_LifeMin3                    1062
#define IDC_P_RotateMinX                1062
#define IDC_R_onDiffuse                 1062
#define IDC_LifeMax3                    1063
#define IDC_P_RotateMaxX                1063
#define IDC_R_onNormalMap               1063
#define IDC_P_isRepeat                  1064
#define IDC_R_onHeightMap               1064
#define IDC_R_onEtc                     1065
#define IDC_P_PositionMaxX              1065
#define IDC_LifeMin5                    1066
#define IDC_P_SpeedMin                  1066
#define IDC_COMBO1                      1066
#define IDC_R_EnviType                  1066
#define IDC_LifeMax5                    1067
#define IDC_P_SpeedMax                  1067
#define IDC_R_ColorX                    1067
#define IDC_LifeMin6                    1068
#define IDC_P_AccelSpeedMin             1068
#define IDC_R_onEffect                  1068
#define IDC_LifeMax6                    1069
#define IDC_P_AccelSpeedMax             1069
#define IDC_R_onEtc2                    1069
#define IDC_R_onSprite                  1069
#define IDC_LifeMin7                    1070
#define IDC_P_GravityMin                1070
#define IDC_R_onEffect3d                1070
#define IDC_LifeMax7                    1071
#define IDC_P_GravityMax                1071
#define IDC_LifeMin8                    1072
#define IDC_P_MaxSpeedMin               1072
#define IDC_LifeMax8                    1073
#define IDC_P_MaxSpeedMax               1073
#define IDC_P_isEnable                  1074
#define ID_SetProto                     1075
#define IDC_P_ScaleMinX                 1075
#define IDC_P_isEnable2                 1075
#define IDC_P_ScaleMaxX                 1076
#define IDC_P_RotationMinX              1077
#define IDC_LifeMin2                    1078
#define IDC_P_DirMinY                   1078
#define IDC_R_HeightCellSize            1078
#define IDC_LifeMin11                   1079
#define IDC_P_DirMinZ                   1079
#define IDC_R_OffsetX                   1079
#define IDC_C_Radius                    1079
#define IDC_LifeMin12                   1080
#define IDC_P_DirMaxY                   1080
#define IDC_R_OffsetX2                  1080
#define IDC_R_OffsetY                   1080
#define IDC_C_MinX                      1080
#define IDC_LifeMin13                   1081
#define IDC_P_DirMaxZ                   1081
#define IDC_R_SpriteFrame               1081
#define IDC_C_MinY                      1081
#define IDC_LifeMin4                    1082
#define IDC_P_RotateMinY                1082
#define IDC_R_StartOffsetX              1082
#define IDC_C_MinZ                      1082
#define IDC_LifeMin14                   1083
#define IDC_P_RotateMinZ                1083
#define IDC_R_StartOffsetY              1083
#define ID_C_Apply                      1083
#define IDC_LifeMin15                   1084
#define IDC_P_RotateMaxY                1084
#define IDC_R_SpriteFrame2              1084
#define IDC_R_SpriteCount               1084
#define IDC_T_PosX                      1084
#define IDC_LifeMin16                   1085
#define IDC_P_RotateMaxZ                1085
#define IDC_R_ShadowRate                1085
#define IDC_T_PosY                      1085
#define IDC_LifeMin9                    1086
#define IDC_P_LifeMin                   1086
#define IDC_R_LightRate                 1086
#define IDC_R_SpriteFrame4              1086
#define IDC_T_PosZ                      1086
#define IDC_LifeMax9                    1087
#define IDC_P_LifeMax                   1087
#define IDC_C_Damping                   1087
#define IDC_T_RotX                      1087
#define IDC_LifeMin10                   1088
#define IDC_P_RotateSpeedMax            1088
#define IDC_C_Repulsion                 1088
#define IDC_T_RotY                      1088
#define IDC_LifeMax10                   1089
#define IDC_P_RotateSpeedMin            1089
#define IDC_C_GravityScale              1089
#define IDC_T_RotZ                      1089
#define IDC_LifeMin17                   1090
#define IDC_P_ColorMinX                 1090
#define IDC_T_ScaleX                    1090
#define IDC_LifeMax4                    1091
#define IDC_P_ColorMaxX                 1091
#define IDC_T_ScaleY                    1091
#define IDC_LifeMin18                   1092
#define IDC_P_ColorMinY                 1092
#define IDC_T_ScaleZ                    1092
#define IDC_LifeMin19                   1093
#define IDC_P_ColorMinZ                 1093
#define ID_T_Apply                      1093
#define IDC_LifeMin20                   1094
#define IDC_P_ColorMaxY                 1094
#define ID_T_Reset                      1094
#define IDC_LifeMin21                   1095
#define IDC_P_ColorMaxZ                 1095
#define IDC_P_ColorMinW                 1096
#define IDC_P_ColorMaxW                 1097
#define IDC_P_PositionMinY              1098
#define IDC_P_PositionMinZ              1099
#define IDC_P_PositionMaxY              1100
#define IDC_P_PositionMaxZ              1101
#define IDC_P_ScaleMinY                 1102
#define IDC_P_ScaleMinZ                 1103
#define IDC_P_ScaleMaxY                 1104
#define IDC_P_ScaleMaxZ                 1105
#define IDC_P_RotationMaxX              1106
#define IDC_P_RotationMinY              1107
#define IDC_P_RotationMinZ              1108
#define IDC_P_RotationMaxY              1109
#define IDC_P_RotationMaxZ              1110
#define IDC_P_isFollow                  1111
#define IDC_P_GravityDirX               1112
#define IDC_P_GravityDirY               1113
#define IDC_P_GravityDirZ               1114
#define IDC_P_ScalePerLifeMinX          1115
#define IDC_P_ScalePerLifeMaxX          1116
#define IDC_P_ScalePerLifeMinY          1117
#define IDC_P_ScalePerLifeMinZ          1118
#define IDC_P_ScalePerLifeMaxY          1119
#define IDC_P_ScalePerLifeMaxZ          1120
#define IDC_P_isScalarScale             1121
#define IDC_P_InitCountMin              1122
#define IDC_P_InitCountMax              1123
#define IDC_P_isRealFollow              1124

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        335
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1095
#define _APS_NEXT_SYMED_VALUE           312
#endif
#endif
